version: '3.8'
services:
  app:
    build: .
    container_name: "confectionary-carnage-backend"
    hostname: "confectionary-carnage-backend"
    ports:
      - "8000:8000"
    restart: always
  postgres:
    image: postgres:latest
    container_name: test_postgres
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"