name: Terraform Apply

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Configure AWS Credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        echo "Configuring AWS credentials..."
        mkdir -p ~/.aws
        echo "[default]" > ~/.aws/credentials
        echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
        echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials


    - name: Terraform Init
      run: |
        cd backend
        terraform init

    - name: Terraform Plan
      env:
        TF_VAR_PG_PORT: ${{ secrets.TF_VAR_PG_PORT }}
        TF_VAR_PG_USER: ${{ secrets.TF_VAR_PG_USER }}
        TF_VAR_PG_PASSWORD: ${{ secrets.TF_VAR_PG_PASSWORD }}
        TF_VAR_PG_DATABASE: ${{ secrets.TF_VAR_PG_DATABASE }}
      run: |
        cd backend
        terraform plan -out=tfplan

    - name: Terraform Apply
      env:
        TF_VAR_PG_PORT: ${{ secrets.TF_VAR_PG_PORT }}
        TF_VAR_PG_USER: ${{ secrets.TF_VAR_PG_USER }}
        TF_VAR_PG_PASSWORD: ${{ secrets.TF_VAR_PG_PASSWORD }}
        TF_VAR_PG_DATABASE: ${{ secrets.TF_VAR_PG_DATABASE }}
      if: github.ref == 'refs/heads/main'
      run: |
        cd backend
        terraform apply -auto-approve tfplan
